---
title: "Homework 2"
author: "Jenn Lewis, Karlena Ochoa, Katie Denning"
date: "2/20/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(gghighlight)
library(tidyverse)
library(dplyr)
library(rio)
library(here)
library(ggrepel)
library(magrittr)
library(lubridate)
#library(psych)
library(stats)
library(devtools)
#install.packages("dplyr")
#remotes::install_github("rstudio/gt")
#devtools::install_github("wilkelab/ungeviz")
library(ungeviz)
library(gt)
library(data.table)


data <- import("https://www.denvergov.org/media/gis/DataCatalog/crime/csv/crime.csv") %>%
  janitor::clean_names()

glimpse(data)

```




```{r Question 1 Replicate Plot}
#Not sure why his graph doesn't have traffic accidents

data_cleaned <- data %>%
  mutate(offense_category_id = str_to_title(offense_category_id)) %>%
  mutate(offense_category_id = recode(offense_category_id, 
                                      "Aggravated-Assault" = "Aggravated Assault",
                                      "All-Other-Crimes" = "All Other Crimes",
                                      "Auto-Theft" = "Auto Theft",
                                      "Drug-Alcohol" = "Drug Alcohol",
                                      "Other-Crimes-Against-Persons" = "Other Crimes Against Persons",
                                      "Public-Disorder" = "Public Disorder",
                                      "Sexual-Assault" = "Sexual Assault",
                                      "Theft-From-Motor-Vehicle" = "Theft From Motor Vehicle",
                                      "Traffic-Accident" = "Traffic Accident",
                                      "White-Collar-Crime" = "White Collar Crime")) %>%
  filter(offense_category_id != "Traffic Accident", is_crime == '1')


crime_percent <- data_cleaned %>%
  count(offense_category_id) %>%
  mutate(Percent = (n/sum(n)),
         prop_se = (sqrt((Percent*(1-Percent)) / n))) 

crime_percent %>%
 ggplot(aes(fct_reorder(offense_category_id, Percent), Percent)) +
  geom_errorbar(aes(ymin = Percent + qnorm(0.025)*prop_se,
                    ymax = Percent + qnorm(0.975)*prop_se)) +
  geom_point(color = "cornflower blue") +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent, limits = c(-0.005, .3)) +
  labs(x = "",
       title = "Crimes in Denver",
       caption = "Denver Crime Data Distributed via Kaggle
       https://www.kaggle.com/paultimothymooney/denver-crime-data")

```


```{r Question 2 Same Relationship Different Uncertainty Visualization}

crime_percent %>%
 ggplot(aes(Percent, fct_reorder(offense_category_id, Percent))) +
  stat_confidence_density(aes(moe = prop_se), 
                          fill = "#4375D3", 
                          height = 0.6,
                          confidence = 0.68) +
  geom_point() +
  theme_minimal() +
  scale_x_continuous(labels = scales::percent, limits = c(-0.005, .3)) +
  labs(x = "",
       title = "Crimes in Denver",
       caption = "Denver Crime Data Distributed via Kaggle
       https://www.kaggle.com/paultimothymooney/denver-crime-data")


```


```{r Question 3 Reproduce plot}

# need crime proortion by district and year. Add error bars to proportions. Extract year. 

df3 <- data %>% 
  select("reported_date", "district_id", "offense_type_id", "offense_category_id") %>% 
  separate(reported_date, c("year", "delete"), sep = " ") %>% 
  select(-"delete") %>% 
  separate(year, c("month", "day", "year"), sep = "/") %>% 
  select(-"month", -"day") %>% 
  mutate(year = as.numeric(year))
  

df4 <- df3 %>% 
  group_by(year, district_id) %>%
  summarise (n = n()) %>%
  mutate(prop = n / sum(n),
         prop_se = (sqrt((prop*(1-prop)) / n)),
         district_id = as.factor(district_id))

#tring to get props
ggplot(df4, aes(fct_reorder(as.factor(district_id), prop), 
                prop, 
                fill = district_id)) +
 geom_col() +
 geom_errorbar(aes(ymin = prop + qnorm(0.025)*prop_se,
              ymax = prop + qnorm(0.975)*prop_se)) +
    coord_flip() +
  theme_minimal() +
  facet_wrap(~year) +
   labs(x = "District",
        y = "Proportion",
        title = "Crimes in Denver",
        caption = "Denver Crime Data Distributed via Kaggle
        https://www.kaggle.com/paultimothymooney/denver-crime-data") +
  theme(legend.position = "none") +
  scale_fill_manual(
    values = c("dodgerblue3", 
               "gold", 
               "palevioletred3", 
               "springgreen4", 
               "skyblue2", 
               "darkorange3", 
               "orange2"),
    breaks = c("3", "6", "1", "2", "4", "5", "7"))

#proportions are correct, just need to finish formatting proportion axis and color order 

```


Limit your data to the following. Note that only rows corresponding to a crime have been retained, and I have counted the number of rows (crimes) for each district in each year. I have stored this data frame in an object called  counts
```{r Question 4 Dot Plot }
#getting data to look like the tibble on the HW
counts <- df4 %>% 
  select(-prop)

#model rovided
m <- glm(n ~ I(factor(district_id)) + I(year - 2014), 
         data = counts)

#output from model
tidied <- broom::tidy(m)

#dividing proportions into 20 bins
ppoints(20)

#Transforming probability according to the crime rate between districts 1 and 4
#Making this into a dataset with a variable indicating crime rate > 0
prob_df <- data.frame(x = qnorm(ppoints(20), 
                                    mean = tidied$estimate[4],
                                    sd = tidied$std.error[4])) %>% 
  mutate(crime_rate_diff = ifelse(x > 0, "orange", "blue"))

ggplot(prob_df, aes(x)) +
  geom_dotplot(aes(fill = crime_rate_diff), binwidth = 1200) +
  geom_vline(xintercept = 0, color = "red4", linetype = 1, size = 1.4) +
  scale_fill_manual(
    values = c("steelblue2", "orange2"),
    guide = "none") +
  scale_x_continuous(limits = c(-8000, 2500),
                     breaks = c(-8000, -6500, -5000, -3500, 
                                -2000, -500, 1000, 2500)) +
  #theme_dviz_open(20) +
  scale_y_continuous(breaks = NULL,
                     name = "") +
  labs(title = "Difference in total number of crimes",
       subtitle = "District 4 Crimes - District 1 Crimes",
       caption = "Each ball represents 5% probability",
       x = "Difference in total number of crimes") +
  theme_minimal() +
  annotate("text", 
           label = "District 4", 
           x = -6500, y = .5, 
           color = "gray40", 
           size = 8) +
  annotate("text", 
           label = "District 1", 
           x = 1500, 
           y = .5, 
           color = "gray40", 
           size = 8)
```


```{r Question 5 Reproduce Table }
df5 <- df3 %>% 
  select(-offense_type_id) %>% 
  filter(district_id == 1 | district_id == 3 | district_id == 5) %>% 
  filter(offense_category_id == "other-crimes-against-persons"| offense_category_id == "murder" |   offense_category_id == "sexual-assault"| offense_category_id == "aggravated-assault") %>%
  mutate(offense_category_id = fct_relevel(offense_category_id, "aggravated-assault", "sexual-assault", "murder", "other-crimes-against-persons"))%>% 
  mutate(offense_category_id = str_to_title(offense_category_id)) %>%
  mutate(offense_category_id = recode(offense_category_id, 
                                      "Aggravated-Assault" = "Aggravated Assault",
                                      "Sexual-Assault" = "Sexual Assault",
                                      "Other-Crimes-Against-Persons" = "Other Crimes Against Persons")) %>% 
  mutate(district_id = str_to_title(district_id)) %>% 
  mutate(district_id = recode(district_id,
                              "1" = "District 1",
                              "3" = "District 3",
                              "5" = "District 5")) 

#prepare data for table format 
summary_df5 <- df5 %>% 
  group_by(year, district_id, offense_category_id) %>%
  count(n = n()) %>% 
  summarize(n = sum(n)) %>% 
  spread(year, n) %>% 
  mutate(offense_category_id = as.factor(offense_category_id)) %>% 
  mutate(offense_category_id = fct_relevel(offense_category_id, "Aggravated Assault", "Sexual Assault", "Murder", "Other Crimes Against Persons"))

setattr(summary_df5$offense_category_id,"levels", c("Aggravated Assault",
                                             "Other Crimes Against Persons",
                                             "Sexual Assault",
                                             "Murder"))

summary_df5 %>%
  gt() %>% 
  tab_spanner(label = "Year",
              columns = vars(`2014`, `2015`, `2016`, `2017`, `2017`, `2018`, `2019`)) %>% 
  cols_label(offense_category_id = "Offense") %>% 
  tab_header(title = "Crimes Against Persons in Denver: 2014 to Present",
             subtitle = (md("*Sample of three districts*"))) %>% 
  tab_source_note(source_note = md("Denver Crime Data Distributed via [Kaggle](https://www.kaggle.com/paultimothymooney/denver-crime-data)")) %>% 
  cols_align(align = "left", columns = vars(offense_category_id))

```

